[SteamClient]
; path to game exe, absolute or relative to the loader
Exe=PRAGMATA.exe
; path to steamclient64.dll, absolute or relative to the loader (default: loader's directory)
SteamClient64Dll=Pragmata/steamclient64.dll
; extra command line arguments for the game
ExeCommandLine=
; Steam App ID, if empty the loader reads steam_settings/steam_appid.txt
AppId=3357650
