[settings]
; This is the steam AppID of the game
appid = 3717070
; This is the path to the steamclient64.dll file
steamclient64 = steamclient64.dll
; This is the delay in seconds before performing cleanup
cleanup_delay = 10